name: opus_banking
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_phoenix: ^0.1.0
  flutter_bloc: ^6.1.1
  http: ^0.12.0+4
  progress_dialog: ^1.2.2
  shared_preferences: ^0.5.7
  google_fonts: ^1.0.0
  font_awesome_flutter: ^8.8.1
  fluttertoast: ^4.0.1
  email_validator: ^1.0.4
  image_picker: ^0.6.6+1
  flutter_datetime_picker: ^1.3.8

  animation_wrappers: ^0.0.1
  international_phone_input: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.1"
  flutter_launcher_name: "^0.0.1"


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter_launcher_name:
  name: "Opus Banking"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/footer icons/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
